CREATE USER DB_ADMIN IDENTIFIED BY "DUSMS@2023dmdd";
GRANT CREATE VIEW TO DB_ADMIN;

CREATE USER DB_CONTENTMGR IDENTIFIED BY "DUSMS@2023cm";
GRANT CREATE VIEW TO DB_CONTENTMGR;

CREATE USER DB_BILLINGMGR IDENTIFIED BY "DUSMS@2023bm";
GRANT CREATE VIEW TO DB_BILLINGMGR;

CREATE USER DB_ANALYST IDENTIFIED BY "DUSMS@2023analyst";
GRANT CREATE VIEW TO DB_ANALYST;

CREATE USER DB_MANAGER IDENTIFIED BY "DUSMS@2023dman";
GRANT CREATE VIEW TO DB_MANAGER;

SELECT * FROM USER_TABLES;

GRANT CONNECT, RESOURCE TO DB_ADMIN;
GRANT CREATE SESSION TO DB_ADMIN;
GRANT UNLIMITED TABLESPACE TO DB_ADMIN;

GRANT CONNECT TO DB_CONTENTMGR;
GRANT INSERT,UPDATE,SELECT ON db_admin.movie TO DB_CONTENTMGR;
GRANT INSERT,UPDATE,SELECT ON db_admin.director TO DB_CONTENTMGR;
GRANT INSERT,UPDATE,SELECT ON db_admin.actor TO DB_CONTENTMGR;
GRANT INSERT,UPDATE,SELECT ON db_admin.subtitles TO DB_CONTENTMGR;
GRANT INSERT,UPDATE,SELECT ON db_admin.genre TO DB_CONTENTMGR;
GRANT INSERT,UPDATE,SELECT ON db_admin.movie_cast TO DB_CONTENTMGR;
GRANT INSERT,UPDATE,SELECT ON db_admin.watch_history TO DB_CONTENTMGR;
GRANT INSERT,UPDATE,SELECT ON db_admin.watchlist TO DB_CONTENTMGR;

GRANT CONNECT TO DB_BILLINGMGR;
GRANT INSERT,UPDATE,SELECT ON db_admin.CUSTOMER TO DB_BILLINGMGR;
GRANT INSERT,UPDATE,SELECT ON db_admin.SUBSCRIPTION_PLAN TO DB_BILLINGMGR;
GRANT INSERT,UPDATE,SELECT ON db_admin.PURCHASE TO DB_BILLINGMGR;

GRANT SELECT on db_admin.customer TO DB_ANALYST;
GRANT SELECT on db_admin.watchlist TO DB_ANALYST;
GRANT SELECT on db_admin.download TO DB_ANALYST;
GRANT SELECT on db_admin.watch_history TO DB_ANALYST;
GRANT SELECT on db_admin.favorite TO DB_ANALYST;
GRANT SELECT on db_admin.movie TO DB_ANALYST;
GRANT SELECT on db_admin.address TO DB_ANALYST;
GRANT SELECT on db_admin.genre to DB_ANALYST;
GRANT SELECT on db_admin.purchase to DB_ANALYST;
GRANT SELECT on db_admin.director to DB_ANALYST;
GRANT SELECT on db_admin.movie_cast to DB_ANALYST;
GRANT SELECT on db_admin.actor to DB_ANALYST;
GRANT SELECT on db_admin.subscription_plan to DB_ANALYST;

GRANT SELECT, INSERT, UPDATE ON db_admin.actor TO DB_MANAGER;
GRANT SELECT, INSERT, UPDATE ON db_admin.address TO DB_MANAGER;
GRANT SELECT, INSERT, UPDATE ON db_admin.director TO DB_MANAGER;
GRANT SELECT, INSERT, UPDATE ON db_admin.download TO DB_MANAGER;
GRANT SELECT, INSERT, UPDATE ON db_admin.favorite TO DB_MANAGER;
GRANT SELECT, INSERT, UPDATE ON db_admin.genre TO DB_MANAGER;
GRANT SELECT, INSERT, UPDATE ON db_admin.movie TO DB_MANAGER;
GRANT SELECT, INSERT, UPDATE ON db_admin.movie_cast TO DB_MANAGER;
GRANT SELECT, INSERT, UPDATE ON db_admin.purchase TO DB_MANAGER;
GRANT SELECT, INSERT, UPDATE ON db_admin.region TO DB_MANAGER;
GRANT SELECT, INSERT, UPDATE ON db_admin.subscription_plan TO DB_MANAGER;
GRANT SELECT, INSERT, UPDATE ON db_admin.subtitles TO DB_MANAGER;
GRANT SELECT, INSERT, UPDATE ON db_admin.watch_history TO DB_MANAGER;
GRANT SELECT, INSERT, UPDATE ON db_admin.watchlist TO DB_MANAGER;
GRANT SELECT,INSERT, UPDATE ON db_admin.customer TO DB_MANAGER;
