insert into REGION (Region_ID, MOVIE_ID, Country Name) values (1, 159, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (2, 196, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (3, 267, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (4, 133, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (5, 187, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (6, 293, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (7, 127, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (8, 283, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (9, 163, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (10, 252, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (11, 295, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (12, 58, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (13, 10, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (14, 270, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (15, 71, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (16, 114, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (17, 250, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (18, 203, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (19, 168, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (20, 122, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (21, 269, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (22, 102, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (23, 243, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (24, 101, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (25, 72, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (26, 285, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (27, 200, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (28, 149, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (29, 67, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (30, 172, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (31, 255, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (32, 62, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (33, 262, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (34, 254, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (35, 93, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (36, 67, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (37, 190, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (38, 43, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (39, 176, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (40, 16, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (41, 87, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (42, 36, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (43, 69, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (44, 96, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (45, 156, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (46, 236, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (47, 41, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (48, 178, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (49, 104, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (50, 266, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (51, 50, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (52, 160, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (53, 107, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (54, 269, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (55, 37, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (56, 138, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (57, 83, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (58, 89, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (59, 294, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (60, 119, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (61, 99, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (62, 51, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (63, 184, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (64, 225, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (65, 244, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (66, 218, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (67, 14, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (68, 42, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (69, 36, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (70, 34, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (71, 55, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (72, 252, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (73, 92, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (74, 179, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (75, 76, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (76, 161, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (77, 133, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (78, 185, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (79, 5, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (80, 299, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (81, 165, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (82, 126, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (83, 196, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (84, 121, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (85, 46, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (86, 21, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (87, 135, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (88, 147, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (89, 273, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (90, 37, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (91, 14, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (92, 227, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (93, 48, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (94, 199, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (95, 4, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (96, 76, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (97, 172, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (98, 187, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (99, 226, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (100, 267, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (101, 153, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (102, 261, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (103, 92, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (104, 38, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (105, 156, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (106, 135, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (107, 20, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (108, 73, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (109, 238, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (110, 42, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (111, 117, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (112, 90, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (113, 297, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (114, 190, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (115, 108, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (116, 84, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (117, 249, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (118, 16, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (119, 191, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (120, 194, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (121, 273, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (122, 247, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (123, 89, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (124, 46, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (125, 161, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (126, 232, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (127, 112, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (128, 143, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (129, 53, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (130, 272, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (131, 121, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (132, 296, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (133, 271, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (134, 203, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (135, 134, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (136, 157, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (137, 62, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (138, 188, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (139, 102, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (140, 209, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (141, 128, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (142, 212, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (143, 89, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (144, 188, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (145, 142, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (146, 12, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (147, 145, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (148, 127, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (149, 13, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (150, 29, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (151, 119, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (152, 68, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (153, 67, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (154, 76, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (155, 202, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (156, 11, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (157, 298, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (158, 154, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (159, 79, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (160, 72, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (161, 167, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (162, 54, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (163, 141, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (164, 29, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (165, 270, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (166, 214, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (167, 142, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (168, 163, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (169, 294, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (170, 266, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (171, 252, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (172, 226, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (173, 181, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (174, 214, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (175, 53, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (176, 13, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (177, 249, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (178, 205, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (179, 138, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (180, 234, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (181, 98, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (182, 281, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (183, 33, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (184, 250, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (185, 124, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (186, 74, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (187, 215, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (188, 150, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (189, 149, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (190, 280, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (191, 165, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (192, 30, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (193, 3, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (194, 37, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (195, 222, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (196, 24, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (197, 69, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (198, 60, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (199, 227, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (200, 151, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (201, 268, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (202, 101, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (203, 36, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (204, 145, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (205, 134, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (206, 223, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (207, 154, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (208, 26, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (209, 208, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (210, 63, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (211, 47, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (212, 172, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (213, 153, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (214, 103, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (215, 78, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (216, 144, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (217, 260, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (218, 44, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (219, 107, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (220, 218, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (221, 21, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (222, 120, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (223, 22, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (224, 87, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (225, 267, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (226, 7, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (227, 145, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (228, 194, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (229, 141, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (230, 128, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (231, 262, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (232, 141, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (233, 32, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (234, 88, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (235, 35, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (236, 293, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (237, 55, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (238, 133, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (239, 35, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (240, 152, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (241, 149, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (242, 152, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (243, 154, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (244, 61, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (245, 151, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (246, 294, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (247, 2, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (248, 140, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (249, 90, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (250, 18, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (251, 71, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (252, 38, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (253, 79, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (254, 294, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (255, 114, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (256, 13, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (257, 272, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (258, 227, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (259, 238, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (260, 171, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (261, 188, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (262, 51, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (263, 185, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (264, 66, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (265, 192, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (266, 12, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (267, 190, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (268, 184, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (269, 160, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (270, 123, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (271, 64, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (272, 241, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (273, 189, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (274, 68, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (275, 239, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (276, 120, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (277, 30, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (278, 295, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (279, 121, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (280, 28, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (281, 14, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (282, 201, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (283, 163, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (284, 263, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (285, 269, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (286, 251, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (287, 152, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (288, 172, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (289, 69, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (290, 175, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (291, 106, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (292, 238, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (293, 289, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (294, 270, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (295, 245, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (296, 140, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (297, 160, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (298, 114, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (299, 297, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (300, 16, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (301, 158, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (302, 278, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (303, 295, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (304, 223, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (305, 250, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (306, 294, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (307, 188, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (308, 229, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (309, 37, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (310, 221, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (311, 198, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (312, 170, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (313, 44, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (314, 221, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (315, 186, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (316, 202, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (317, 46, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (318, 199, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (319, 237, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (320, 170, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (321, 12, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (322, 252, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (323, 231, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (324, 12, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (325, 121, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (326, 55, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (327, 76, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (328, 282, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (329, 116, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (330, 198, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (331, 4, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (332, 42, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (333, 203, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (334, 119, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (335, 264, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (336, 251, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (337, 110, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (338, 165, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (339, 188, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (340, 71, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (341, 26, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (342, 289, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (343, 8, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (344, 298, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (345, 91, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (346, 9, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (347, 53, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (348, 277, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (349, 143, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (350, 272, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (351, 156, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (352, 47, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (353, 19, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (354, 188, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (355, 256, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (356, 115, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (357, 193, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (358, 136, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (359, 281, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (360, 98, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (361, 33, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (362, 123, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (363, 2, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (364, 84, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (365, 113, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (366, 234, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (367, 200, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (368, 132, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (369, 224, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (370, 179, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (371, 177, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (372, 64, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (373, 2, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (374, 121, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (375, 27, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (376, 107, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (377, 159, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (378, 211, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (379, 164, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (380, 72, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (381, 99, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (382, 227, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (383, 259, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (384, 103, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (385, 96, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (386, 126, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (387, 275, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (388, 188, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (389, 272, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (390, 231, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (391, 273, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (392, 294, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (393, 242, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (394, 23, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (395, 221, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (396, 267, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (397, 296, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (398, 270, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (399, 264, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (400, 90, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (401, 21, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (402, 55, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (403, 99, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (404, 249, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (405, 78, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (406, 134, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (407, 251, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (408, 297, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (409, 189, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (410, 25, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (411, 96, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (412, 94, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (413, 272, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (414, 134, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (415, 199, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (416, 186, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (417, 185, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (418, 94, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (419, 153, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (420, 133, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (421, 240, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (422, 33, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (423, 298, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (424, 58, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (425, 84, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (426, 121, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (427, 270, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (428, 261, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (429, 241, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (430, 125, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (431, 111, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (432, 283, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (433, 55, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (434, 2, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (435, 185, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (436, 160, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (437, 7, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (438, 244, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (439, 105, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (440, 220, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (441, 56, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (442, 110, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (443, 248, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (444, 120, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (445, 70, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (446, 124, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (447, 189, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (448, 184, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (449, 100, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (450, 189, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (451, 132, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (452, 181, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (453, 188, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (454, 115, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (455, 3, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (456, 1, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (457, 85, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (458, 42, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (459, 61, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (460, 106, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (461, 192, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (462, 154, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (463, 290, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (464, 82, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (465, 184, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (466, 113, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (467, 49, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (468, 259, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (469, 76, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (470, 246, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (471, 169, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (472, 9, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (473, 236, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (474, 295, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (475, 210, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (476, 108, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (477, 253, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (478, 123, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (479, 173, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (480, 294, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (481, 2, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (482, 10, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (483, 20, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (484, 297, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (485, 241, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (486, 120, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (487, 124, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (488, 71, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (489, 214, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (490, 285, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (491, 84, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (492, 170, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (493, 275, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (494, 277, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (495, 228, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (496, 224, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (497, 101, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (498, 188, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (499, 23, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (500, 98, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (501, 23, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (502, 242, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (503, 117, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (504, 26, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (505, 87, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (506, 240, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (507, 19, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (508, 216, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (509, 278, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (510, 15, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (511, 139, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (512, 187, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (513, 188, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (514, 175, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (515, 272, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (516, 268, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (517, 61, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (518, 234, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (519, 199, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (520, 115, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (521, 149, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (522, 288, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (523, 135, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (524, 139, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (525, 1, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (526, 106, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (527, 210, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (528, 45, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (529, 69, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (530, 41, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (531, 123, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (532, 115, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (533, 134, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (534, 88, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (535, 211, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (536, 73, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (537, 191, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (538, 140, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (539, 107, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (540, 72, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (541, 193, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (542, 86, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (543, 103, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (544, 83, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (545, 162, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (546, 221, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (547, 143, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (548, 30, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (549, 238, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (550, 15, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (551, 24, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (552, 271, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (553, 185, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (554, 192, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (555, 235, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (556, 286, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (557, 259, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (558, 200, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (559, 68, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (560, 285, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (561, 238, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (562, 211, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (563, 300, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (564, 75, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (565, 136, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (566, 123, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (567, 66, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (568, 90, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (569, 8, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (570, 67, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (571, 223, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (572, 160, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (573, 84, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (574, 207, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (575, 89, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (576, 102, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (577, 77, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (578, 179, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (579, 240, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (580, 146, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (581, 216, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (582, 142, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (583, 185, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (584, 56, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (585, 104, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (586, 25, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (587, 4, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (588, 234, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (589, 69, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (590, 77, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (591, 91, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (592, 111, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (593, 32, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (594, 176, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (595, 269, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (596, 220, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (597, 125, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (598, 37, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (599, 244, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (600, 174, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (601, 205, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (602, 109, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (603, 145, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (604, 44, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (605, 139, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (606, 77, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (607, 212, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (608, 36, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (609, 116, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (610, 67, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (611, 156, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (612, 73, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (613, 189, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (614, 237, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (615, 56, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (616, 67, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (617, 185, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (618, 109, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (619, 103, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (620, 98, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (621, 119, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (622, 174, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (623, 41, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (624, 40, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (625, 67, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (626, 120, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (627, 276, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (628, 237, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (629, 287, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (630, 300, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (631, 263, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (632, 123, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (633, 271, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (634, 267, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (635, 54, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (636, 211, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (637, 55, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (638, 237, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (639, 29, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (640, 148, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (641, 118, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (642, 143, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (643, 297, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (644, 96, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (645, 67, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (646, 64, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (647, 107, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (648, 115, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (649, 92, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (650, 208, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (651, 100, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (652, 248, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (653, 211, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (654, 221, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (655, 25, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (656, 24, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (657, 58, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (658, 223, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (659, 95, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (660, 145, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (661, 63, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (662, 170, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (663, 154, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (664, 189, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (665, 31, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (666, 49, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (667, 291, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (668, 25, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (669, 17, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (670, 125, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (671, 225, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (672, 271, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (673, 206, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (674, 208, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (675, 216, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (676, 201, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (677, 190, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (678, 45, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (679, 107, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (680, 227, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (681, 20, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (682, 204, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (683, 128, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (684, 26, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (685, 164, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (686, 113, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (687, 122, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (688, 189, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (689, 8, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (690, 123, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (691, 237, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (692, 188, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (693, 215, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (694, 239, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (695, 51, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (696, 52, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (697, 190, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (698, 147, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (699, 227, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (700, 291, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (701, 216, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (702, 48, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (703, 42, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (704, 269, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (705, 168, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (706, 197, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (707, 49, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (708, 203, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (709, 5, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (710, 90, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (711, 240, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (712, 102, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (713, 275, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (714, 202, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (715, 178, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (716, 201, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (717, 173, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (718, 225, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (719, 229, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (720, 133, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (721, 251, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (722, 228, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (723, 180, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (724, 203, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (725, 102, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (726, 177, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (727, 76, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (728, 163, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (729, 66, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (730, 73, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (731, 289, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (732, 182, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (733, 180, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (734, 92, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (735, 33, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (736, 175, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (737, 57, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (738, 290, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (739, 21, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (740, 149, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (741, 201, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (742, 80, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (743, 240, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (744, 96, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (745, 45, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (746, 31, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (747, 290, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (748, 24, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (749, 11, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (750, 208, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (751, 264, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (752, 64, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (753, 203, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (754, 221, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (755, 263, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (756, 165, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (757, 158, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (758, 289, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (759, 121, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (760, 73, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (761, 293, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (762, 120, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (763, 7, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (764, 235, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (765, 134, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (766, 225, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (767, 141, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (768, 202, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (769, 176, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (770, 293, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (771, 249, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (772, 239, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (773, 134, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (774, 4, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (775, 277, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (776, 175, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (777, 165, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (778, 293, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (779, 221, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (780, 279, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (781, 129, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (782, 285, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (783, 39, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (784, 212, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (785, 200, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (786, 181, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (787, 198, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (788, 147, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (789, 198, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (790, 67, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (791, 192, 'USA');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (792, 227, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (793, 24, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (794, 192, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (795, 57, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (796, 154, 'India');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (797, 280, 'Canada');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (798, 183, 'United Kingdom');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (799, 26, 'Australia');
insert into REGION (Region_ID, MOVIE_ID, Country Name) values (800, 279, 'Australia');
